package com.pokemonlisting.service;

import org.springframework.stereotype.Service;
import java.util.HashMap;
import java.util.Map;

@Service
public class PokemonDexService {

    private final Map<Integer, String> dexIdToName;

    public PokemonDexService() {
        dexIdToName = new HashMap<>();
        initializePokemonNames();
    }

    /**
     * Gets the Pokémon name for a given Pokédex ID.
     *
     * @param dexId Pokédex number (1-1025)
     * @return Pokémon name, or null if not found
     */
    public String getName(int dexId) {
        return dexIdToName.get(dexId);
    }

    /**
     * Checks if a Pokédex ID is valid.
     *
     * @param dexId Pokédex number
     * @return true if valid Pokémon exists
     */
    public boolean isValidDexId(int dexId) {
        return dexIdToName.containsKey(dexId);
    }

    /**
     * Validates if an extracted name matches the expected Pokémon name.
     * Case-insensitive comparison.
     *
     * @param extractedName Name from OCR
     * @param dexId Pokédex ID from card
     * @return true if names match (ignoring case and common suffixes)
     */
    public boolean validateName(String extractedName, int dexId) {
        if (extractedName == null || !isValidDexId(dexId)) {
            return false;
        }

        String expectedName = getName(dexId);
        if (expectedName == null) {
            return false;
        }

        // Normalize both names (lowercase, remove common suffixes)
        String normalizedExtracted = normalizeName(extractedName);
        String normalizedExpected = normalizeName(expectedName);

        return normalizedExtracted.equals(normalizedExpected);
    }

    /**
     * Normalizes a Pokémon name for comparison.
     * Removes common suffixes like "ex", "V", "VMAX", etc.
     *
     * @param name Card name
     * @return Normalized name
     */
    private String normalizeName(String name) {
        if (name == null) {
            return "";
        }
        String normalized = name.toLowerCase().trim();

        // Remove common card suffixes
        normalized = normalized.replaceAll("\\s+(ex|v|vmax|vstar|gx|break)$", "");

        // Remove possessive forms (e.g., "Team Rocket's")
        normalized = normalized.replaceAll("^.*'s\\s+", "");
        normalized = normalized.replaceAll("^.*'s\\s+", "");

        return normalized;
    }

    /**
     * Initialize the complete Pokémon name mapping (Generations 1-9).
     * Total: 1025 Pokémon
     */
    private void initializePokemonNames() {
        // Generation 1 (1-151)
        dexIdToName.put(1, "Bulbasaur");
        dexIdToName.put(2, "Ivysaur");
        dexIdToName.put(3, "Venusaur");
        dexIdToName.put(4, "Charmander");
        dexIdToName.put(5, "Charmeleon");
        dexIdToName.put(6, "Charizard");
        dexIdToName.put(7, "Squirtle");
        dexIdToName.put(8, "Wartortle");
        dexIdToName.put(9, "Blastoise");
        dexIdToName.put(10, "Caterpie");
        dexIdToName.put(11, "Metapod");
        dexIdToName.put(12, "Butterfree");
        dexIdToName.put(13, "Weedle");
        dexIdToName.put(14, "Kakuna");
        dexIdToName.put(15, "Beedrill");
        dexIdToName.put(16, "Pidgey");
        dexIdToName.put(17, "Pidgeotto");
        dexIdToName.put(18, "Pidgeot");
        dexIdToName.put(19, "Rattata");
        dexIdToName.put(20, "Raticate");
        dexIdToName.put(21, "Spearow");
        dexIdToName.put(22, "Fearow");
        dexIdToName.put(23, "Ekans");
        dexIdToName.put(24, "Arbok");
        dexIdToName.put(25, "Pikachu");
        dexIdToName.put(26, "Raichu");
        dexIdToName.put(27, "Sandshrew");
        dexIdToName.put(28, "Sandslash");
        dexIdToName.put(29, "Nidoran♀");
        dexIdToName.put(30, "Nidorina");
        dexIdToName.put(31, "Nidoqueen");
        dexIdToName.put(32, "Nidoran♂");
        dexIdToName.put(33, "Nidorino");
        dexIdToName.put(34, "Nidoking");
        dexIdToName.put(35, "Clefairy");
        dexIdToName.put(36, "Clefable");
        dexIdToName.put(37, "Vulpix");
        dexIdToName.put(38, "Ninetales");
        dexIdToName.put(39, "Jigglypuff");
        dexIdToName.put(40, "Wigglytuff");
        dexIdToName.put(41, "Zubat");
        dexIdToName.put(42, "Golbat");
        dexIdToName.put(43, "Oddish");
        dexIdToName.put(44, "Gloom");
        dexIdToName.put(45, "Vileplume");
        dexIdToName.put(46, "Paras");
        dexIdToName.put(47, "Parasect");
        dexIdToName.put(48, "Venonat");
        dexIdToName.put(49, "Venomoth");
        dexIdToName.put(50, "Diglett");
        dexIdToName.put(51, "Dugtrio");
        dexIdToName.put(52, "Meowth");
        dexIdToName.put(53, "Persian");
        dexIdToName.put(54, "Psyduck");
        dexIdToName.put(55, "Golduck");
        dexIdToName.put(56, "Mankey");
        dexIdToName.put(57, "Primeape");
        dexIdToName.put(58, "Growlithe");
        dexIdToName.put(59, "Arcanine");
        dexIdToName.put(60, "Poliwag");
        dexIdToName.put(61, "Poliwhirl");
        dexIdToName.put(62, "Poliwrath");
        dexIdToName.put(63, "Abra");
        dexIdToName.put(64, "Kadabra");
        dexIdToName.put(65, "Alakazam");
        dexIdToName.put(66, "Machop");
        dexIdToName.put(67, "Machoke");
        dexIdToName.put(68, "Machamp");
        dexIdToName.put(69, "Bellsprout");
        dexIdToName.put(70, "Weepinbell");
        dexIdToName.put(71, "Victreebel");
        dexIdToName.put(72, "Tentacool");
        dexIdToName.put(73, "Tentacruel");
        dexIdToName.put(74, "Geodude");
        dexIdToName.put(75, "Graveler");
        dexIdToName.put(76, "Golem");
        dexIdToName.put(77, "Ponyta");
        dexIdToName.put(78, "Rapidash");
        dexIdToName.put(79, "Slowpoke");
        dexIdToName.put(80, "Slowbro");
        dexIdToName.put(81, "Magnemite");
        dexIdToName.put(82, "Magneton");
        dexIdToName.put(83, "Farfetch'd");
        dexIdToName.put(84, "Doduo");
        dexIdToName.put(85, "Dodrio");
        dexIdToName.put(86, "Seel");
        dexIdToName.put(87, "Dewgong");
        dexIdToName.put(88, "Grimer");
        dexIdToName.put(89, "Muk");
        dexIdToName.put(90, "Shellder");
        dexIdToName.put(91, "Cloyster");
        dexIdToName.put(92, "Gastly");
        dexIdToName.put(93, "Haunter");
        dexIdToName.put(94, "Gengar");
        dexIdToName.put(95, "Onix");
        dexIdToName.put(96, "Drowzee");
        dexIdToName.put(97, "Hypno");
        dexIdToName.put(98, "Krabby");
        dexIdToName.put(99, "Kingler");
        dexIdToName.put(100, "Voltorb");
        dexIdToName.put(101, "Electrode");
        dexIdToName.put(102, "Exeggcute");
        dexIdToName.put(103, "Exeggutor");
        dexIdToName.put(104, "Cubone");
        dexIdToName.put(105, "Marowak");
        dexIdToName.put(106, "Hitmonlee");
        dexIdToName.put(107, "Hitmonchan");
        dexIdToName.put(108, "Lickitung");
        dexIdToName.put(109, "Koffing");
        dexIdToName.put(110, "Weezing");
        dexIdToName.put(111, "Rhyhorn");
        dexIdToName.put(112, "Rhydon");
        dexIdToName.put(113, "Chansey");
        dexIdToName.put(114, "Tangela");
        dexIdToName.put(115, "Kangaskhan");
        dexIdToName.put(116, "Horsea");
        dexIdToName.put(117, "Seadra");
        dexIdToName.put(118, "Goldeen");
        dexIdToName.put(119, "Seaking");
        dexIdToName.put(120, "Staryu");
        dexIdToName.put(121, "Starmie");
        dexIdToName.put(122, "Mr. Mime");
        dexIdToName.put(123, "Scyther");
        dexIdToName.put(124, "Jynx");
        dexIdToName.put(125, "Electabuzz");
        dexIdToName.put(126, "Magmar");
        dexIdToName.put(127, "Pinsir");
        dexIdToName.put(128, "Tauros");
        dexIdToName.put(129, "Magikarp");
        dexIdToName.put(130, "Gyarados");
        dexIdToName.put(131, "Lapras");
        dexIdToName.put(132, "Ditto");
        dexIdToName.put(133, "Eevee");
        dexIdToName.put(134, "Vaporeon");
        dexIdToName.put(135, "Jolteon");
        dexIdToName.put(136, "Flareon");
        dexIdToName.put(137, "Porygon");
        dexIdToName.put(138, "Omanyte");
        dexIdToName.put(139, "Omastar");
        dexIdToName.put(140, "Kabuto");
        dexIdToName.put(141, "Kabutops");
        dexIdToName.put(142, "Aerodactyl");
        dexIdToName.put(143, "Snorlax");
        dexIdToName.put(144, "Articuno");
        dexIdToName.put(145, "Zapdos");
        dexIdToName.put(146, "Moltres");
        dexIdToName.put(147, "Dratini");
        dexIdToName.put(148, "Dragonair");
        dexIdToName.put(149, "Dragonite");
        dexIdToName.put(150, "Mewtwo");
        dexIdToName.put(151, "Mew");

        // Generation 2 (152-251)
        dexIdToName.put(152, "Chikorita");
        dexIdToName.put(153, "Bayleef");
        dexIdToName.put(154, "Meganium");
        dexIdToName.put(155, "Cyndaquil");
        dexIdToName.put(156, "Quilava");
        dexIdToName.put(157, "Typhlosion");
        dexIdToName.put(158, "Totodile");
        dexIdToName.put(159, "Croconaw");
        dexIdToName.put(160, "Feraligatr");
        dexIdToName.put(161, "Sentret");
        dexIdToName.put(162, "Furret");
        dexIdToName.put(163, "Hoothoot");
        dexIdToName.put(164, "Noctowl");
        dexIdToName.put(165, "Ledyba");
        dexIdToName.put(166, "Ledian");
        dexIdToName.put(167, "Spinarak");
        dexIdToName.put(168, "Ariados");
        dexIdToName.put(169, "Crobat");
        dexIdToName.put(170, "Chinchou");
        dexIdToName.put(171, "Lanturn");
        dexIdToName.put(172, "Pichu");
        dexIdToName.put(173, "Cleffa");
        dexIdToName.put(174, "Igglybuff");
        dexIdToName.put(175, "Togepi");
        dexIdToName.put(176, "Togetic");
        dexIdToName.put(177, "Natu");
        dexIdToName.put(178, "Xatu");
        dexIdToName.put(179, "Mareep");
        dexIdToName.put(180, "Flaaffy");
        dexIdToName.put(181, "Ampharos");
        dexIdToName.put(182, "Bellossom");
        dexIdToName.put(183, "Marill");
        dexIdToName.put(184, "Azumarill");
        dexIdToName.put(185, "Sudowoodo");
        dexIdToName.put(186, "Politoed");
        dexIdToName.put(187, "Hoppip");
        dexIdToName.put(188, "Skiploom");
        dexIdToName.put(189, "Jumpluff");
        dexIdToName.put(190, "Aipom");
        dexIdToName.put(191, "Sunkern");
        dexIdToName.put(192, "Sunflora");
        dexIdToName.put(193, "Yanma");
        dexIdToName.put(194, "Wooper");
        dexIdToName.put(195, "Quagsire");
        dexIdToName.put(196, "Espeon");
        dexIdToName.put(197, "Umbreon");
        dexIdToName.put(198, "Murkrow");
        dexIdToName.put(199, "Slowking");
        dexIdToName.put(200, "Misdreavus");
        dexIdToName.put(201, "Unown");
        dexIdToName.put(202, "Wobbuffet");
        dexIdToName.put(203, "Girafarig");
        dexIdToName.put(204, "Pineco");
        dexIdToName.put(205, "Forretress");
        dexIdToName.put(206, "Dunsparce");
        dexIdToName.put(207, "Gligar");
        dexIdToName.put(208, "Steelix");
        dexIdToName.put(209, "Snubbull");
        dexIdToName.put(210, "Granbull");
        dexIdToName.put(211, "Qwilfish");
        dexIdToName.put(212, "Scizor");
        dexIdToName.put(213, "Shuckle");
        dexIdToName.put(214, "Heracross");
        dexIdToName.put(215, "Sneasel");
        dexIdToName.put(216, "Teddiursa");
        dexIdToName.put(217, "Ursaring");
        dexIdToName.put(218, "Slugma");
        dexIdToName.put(219, "Magcargo");
        dexIdToName.put(220, "Swinub");
        dexIdToName.put(221, "Piloswine");
        dexIdToName.put(222, "Corsola");
        dexIdToName.put(223, "Remoraid");
        dexIdToName.put(224, "Octillery");
        dexIdToName.put(225, "Delibird");
        dexIdToName.put(226, "Mantine");
        dexIdToName.put(227, "Skarmory");
        dexIdToName.put(228, "Houndour");
        dexIdToName.put(229, "Houndoom");
        dexIdToName.put(230, "Kingdra");
        dexIdToName.put(231, "Phanpy");
        dexIdToName.put(232, "Donphan");
        dexIdToName.put(233, "Porygon2");
        dexIdToName.put(234, "Stantler");
        dexIdToName.put(235, "Smeargle");
        dexIdToName.put(236, "Tyrogue");
        dexIdToName.put(237, "Hitmontop");
        dexIdToName.put(238, "Smoochum");
        dexIdToName.put(239, "Elekid");
        dexIdToName.put(240, "Magby");
        dexIdToName.put(241, "Miltank");
        dexIdToName.put(242, "Blissey");
        dexIdToName.put(243, "Raikou");
        dexIdToName.put(244, "Entei");
        dexIdToName.put(245, "Suicune");
        dexIdToName.put(246, "Larvitar");
        dexIdToName.put(247, "Pupitar");
        dexIdToName.put(248, "Tyranitar");
        dexIdToName.put(249, "Lugia");
        dexIdToName.put(250, "Ho-Oh");
        dexIdToName.put(251, "Celebi");

        // Generation 3 (252-386)
        dexIdToName.put(252, "Treecko");
        dexIdToName.put(253, "Grovyle");
        dexIdToName.put(254, "Sceptile");
        dexIdToName.put(255, "Torchic");
        dexIdToName.put(256, "Combusken");
        dexIdToName.put(257, "Blaziken");
        dexIdToName.put(258, "Mudkip");
        dexIdToName.put(259, "Marshtomp");
        dexIdToName.put(260, "Swampert");
        dexIdToName.put(261, "Poochyena");
        dexIdToName.put(262, "Mightyena");
        dexIdToName.put(263, "Zigzagoon");
        dexIdToName.put(264, "Linoone");
        dexIdToName.put(265, "Wurmple");
        dexIdToName.put(266, "Silcoon");
        dexIdToName.put(267, "Beautifly");
        dexIdToName.put(268, "Cascoon");
        dexIdToName.put(269, "Dustox");
        dexIdToName.put(270, "Lotad");
        dexIdToName.put(271, "Lombre");
        dexIdToName.put(272, "Ludicolo");
        dexIdToName.put(273, "Seedot");
        dexIdToName.put(274, "Nuzleaf");
        dexIdToName.put(275, "Shiftry");
        dexIdToName.put(276, "Taillow");
        dexIdToName.put(277, "Swellow");
        dexIdToName.put(278, "Wingull");
        dexIdToName.put(279, "Pelipper");
        dexIdToName.put(280, "Ralts");
        dexIdToName.put(281, "Kirlia");
        dexIdToName.put(282, "Gardevoir");
        dexIdToName.put(283, "Surskit");
        dexIdToName.put(284, "Masquerain");
        dexIdToName.put(285, "Shroomish");
        dexIdToName.put(286, "Breloom");
        dexIdToName.put(287, "Slakoth");
        dexIdToName.put(288, "Vigoroth");
        dexIdToName.put(289, "Slaking");
        dexIdToName.put(290, "Nincada");
        dexIdToName.put(291, "Ninjask");
        dexIdToName.put(292, "Shedinja");
        dexIdToName.put(293, "Whismur");
        dexIdToName.put(294, "Loudred");
        dexIdToName.put(295, "Exploud");
        dexIdToName.put(296, "Makuhita");
        dexIdToName.put(297, "Hariyama");
        dexIdToName.put(298, "Azurill");
        dexIdToName.put(299, "Nosepass");
        dexIdToName.put(300, "Skitty");
        dexIdToName.put(301, "Delcatty");
        dexIdToName.put(302, "Sableye");
        dexIdToName.put(303, "Mawile");
        dexIdToName.put(304, "Aron");
        dexIdToName.put(305, "Lairon");
        dexIdToName.put(306, "Aggron");
        dexIdToName.put(307, "Meditite");
        dexIdToName.put(308, "Medicham");
        dexIdToName.put(309, "Electrike");
        dexIdToName.put(310, "Manectric");
        dexIdToName.put(311, "Plusle");
        dexIdToName.put(312, "Minun");
        dexIdToName.put(313, "Volbeat");
        dexIdToName.put(314, "Illumise");
        dexIdToName.put(315, "Roselia");
        dexIdToName.put(316, "Gulpin");
        dexIdToName.put(317, "Swalot");
        dexIdToName.put(318, "Carvanha");
        dexIdToName.put(319, "Sharpedo");
        dexIdToName.put(320, "Wailmer");
        dexIdToName.put(321, "Wailord");
        dexIdToName.put(322, "Numel");
        dexIdToName.put(323, "Camerupt");
        dexIdToName.put(324, "Torkoal");
        dexIdToName.put(325, "Spoink");
        dexIdToName.put(326, "Grumpig");
        dexIdToName.put(327, "Spinda");
        dexIdToName.put(328, "Trapinch");
        dexIdToName.put(329, "Vibrava");
        dexIdToName.put(330, "Flygon");
        dexIdToName.put(331, "Cacnea");
        dexIdToName.put(332, "Cacturne");
        dexIdToName.put(333, "Swablu");
        dexIdToName.put(334, "Altaria");
        dexIdToName.put(335, "Zangoose");
        dexIdToName.put(336, "Seviper");
        dexIdToName.put(337, "Lunatone");
        dexIdToName.put(338, "Solrock");
        dexIdToName.put(339, "Barboach");
        dexIdToName.put(340, "Whiscash");
        dexIdToName.put(341, "Corphish");
        dexIdToName.put(342, "Crawdaunt");
        dexIdToName.put(343, "Baltoy");
        dexIdToName.put(344, "Claydol");
        dexIdToName.put(345, "Lileep");
        dexIdToName.put(346, "Cradily");
        dexIdToName.put(347, "Anorith");
        dexIdToName.put(348, "Armaldo");
        dexIdToName.put(349, "Feebas");
        dexIdToName.put(350, "Milotic");
        dexIdToName.put(351, "Castform");
        dexIdToName.put(352, "Kecleon");
        dexIdToName.put(353, "Shuppet");
        dexIdToName.put(354, "Banette");
        dexIdToName.put(355, "Duskull");
        dexIdToName.put(356, "Dusclops");
        dexIdToName.put(357, "Tropius");
        dexIdToName.put(358, "Chimecho");
        dexIdToName.put(359, "Absol");
        dexIdToName.put(360, "Wynaut");
        dexIdToName.put(361, "Snorunt");
        dexIdToName.put(362, "Glalie");
        dexIdToName.put(363, "Spheal");
        dexIdToName.put(364, "Sealeo");
        dexIdToName.put(365, "Walrein");
        dexIdToName.put(366, "Clamperl");
        dexIdToName.put(367, "Huntail");
        dexIdToName.put(368, "Gorebyss");
        dexIdToName.put(369, "Relicanth");
        dexIdToName.put(370, "Luvdisc");
        dexIdToName.put(371, "Bagon");
        dexIdToName.put(372, "Shelgon");
        dexIdToName.put(373, "Salamence");
        dexIdToName.put(374, "Beldum");
        dexIdToName.put(375, "Metang");
        dexIdToName.put(376, "Metagross");
        dexIdToName.put(377, "Regirock");
        dexIdToName.put(378, "Regice");
        dexIdToName.put(379, "Registeel");
        dexIdToName.put(380, "Latias");
        dexIdToName.put(381, "Latios");
        dexIdToName.put(382, "Kyogre");
        dexIdToName.put(383, "Groudon");
        dexIdToName.put(384, "Rayquaza");
        dexIdToName.put(385, "Jirachi");
        dexIdToName.put(386, "Deoxys");

        // Generation 4 (387-493)
        dexIdToName.put(387, "Turtwig");
        dexIdToName.put(388, "Grotle");
        dexIdToName.put(389, "Torterra");
        dexIdToName.put(390, "Chimchar");
        dexIdToName.put(391, "Monferno");
        dexIdToName.put(392, "Infernape");
        dexIdToName.put(393, "Piplup");
        dexIdToName.put(394, "Prinplup");
        dexIdToName.put(395, "Empoleon");
        dexIdToName.put(396, "Starly");
        dexIdToName.put(397, "Staravia");
        dexIdToName.put(398, "Staraptor");
        dexIdToName.put(399, "Bidoof");
        dexIdToName.put(400, "Bibarel");
        dexIdToName.put(401, "Kricketot");
        dexIdToName.put(402, "Kricketune");
        dexIdToName.put(403, "Shinx");
        dexIdToName.put(404, "Luxio");
        dexIdToName.put(405, "Luxray");
        dexIdToName.put(406, "Budew");
        dexIdToName.put(407, "Roserade");
        dexIdToName.put(408, "Cranidos");
        dexIdToName.put(409, "Rampardos");
        dexIdToName.put(410, "Shieldon");
        dexIdToName.put(411, "Bastiodon");
        dexIdToName.put(412, "Burmy");
        dexIdToName.put(413, "Wormadam");
        dexIdToName.put(414, "Mothim");
        dexIdToName.put(415, "Combee");
        dexIdToName.put(416, "Vespiquen");
        dexIdToName.put(417, "Pachirisu");
        dexIdToName.put(418, "Buizel");
        dexIdToName.put(419, "Floatzel");
        dexIdToName.put(420, "Cherubi");
        dexIdToName.put(421, "Cherrim");
        dexIdToName.put(422, "Shellos");
        dexIdToName.put(423, "Gastrodon");
        dexIdToName.put(424, "Ambipom");
        dexIdToName.put(425, "Drifloon");
        dexIdToName.put(426, "Drifblim");
        dexIdToName.put(427, "Buneary");
        dexIdToName.put(428, "Lopunny");
        dexIdToName.put(429, "Mismagius");
        dexIdToName.put(430, "Honchkrow");
        dexIdToName.put(431, "Glameow");
        dexIdToName.put(432, "Purugly");
        dexIdToName.put(433, "Chingling");
        dexIdToName.put(434, "Stunky");
        dexIdToName.put(435, "Skuntank");
        dexIdToName.put(436, "Bronzor");
        dexIdToName.put(437, "Bronzong");
        dexIdToName.put(438, "Bonsly");
        dexIdToName.put(439, "Mime Jr.");
        dexIdToName.put(440, "Happiny");
        dexIdToName.put(441, "Chatot");
        dexIdToName.put(442, "Spiritomb");
        dexIdToName.put(443, "Gible");
        dexIdToName.put(444, "Gabite");
        dexIdToName.put(445, "Garchomp");
        dexIdToName.put(446, "Munchlax");
        dexIdToName.put(447, "Riolu");
        dexIdToName.put(448, "Lucario");
        dexIdToName.put(449, "Hippopotas");
        dexIdToName.put(450, "Hippowdon");
        dexIdToName.put(451, "Skorupi");
        dexIdToName.put(452, "Drapion");
        dexIdToName.put(453, "Croagunk");
        dexIdToName.put(454, "Toxicroak");
        dexIdToName.put(455, "Carnivine");
        dexIdToName.put(456, "Finneon");
        dexIdToName.put(457, "Lumineon");
        dexIdToName.put(458, "Mantyke");
        dexIdToName.put(459, "Snover");
        dexIdToName.put(460, "Abomasnow");
        dexIdToName.put(461, "Weavile");
        dexIdToName.put(462, "Magnezone");
        dexIdToName.put(463, "Lickilicky");
        dexIdToName.put(464, "Rhyperior");
        dexIdToName.put(465, "Tangrowth");
        dexIdToName.put(466, "Electivire");
        dexIdToName.put(467, "Magmortar");
        dexIdToName.put(468, "Togekiss");
        dexIdToName.put(469, "Yanmega");
        dexIdToName.put(470, "Leafeon");
        dexIdToName.put(471, "Glaceon");
        dexIdToName.put(472, "Gliscor");
        dexIdToName.put(473, "Mamoswine");
        dexIdToName.put(474, "Porygon-Z");
        dexIdToName.put(475, "Gallade");
        dexIdToName.put(476, "Probopass");
        dexIdToName.put(477, "Dusknoir");
        dexIdToName.put(478, "Froslass");
        dexIdToName.put(479, "Rotom");
        dexIdToName.put(480, "Uxie");
        dexIdToName.put(481, "Mesprit");
        dexIdToName.put(482, "Azelf");
        dexIdToName.put(483, "Dialga");
        dexIdToName.put(484, "Palkia");
        dexIdToName.put(485, "Heatran");
        dexIdToName.put(486, "Regigigas");
        dexIdToName.put(487, "Giratina");
        dexIdToName.put(488, "Cresselia");
        dexIdToName.put(489, "Phione");
        dexIdToName.put(490, "Manaphy");
        dexIdToName.put(491, "Darkrai");
        dexIdToName.put(492, "Shaymin");
        dexIdToName.put(493, "Arceus");

        // Generation 5 (494-649)
        dexIdToName.put(494, "Victini");
        dexIdToName.put(495, "Snivy");
        dexIdToName.put(496, "Servine");
        dexIdToName.put(497, "Serperior");
        dexIdToName.put(498, "Tepig");
        dexIdToName.put(499, "Pignite");
        dexIdToName.put(500, "Emboar");
        dexIdToName.put(501, "Oshawott");
        dexIdToName.put(502, "Dewott");
        dexIdToName.put(503, "Samurott");
        dexIdToName.put(504, "Patrat");
        dexIdToName.put(505, "Watchog");
        dexIdToName.put(506, "Lillipup");
        dexIdToName.put(507, "Herdier");
        dexIdToName.put(508, "Stoutland");
        dexIdToName.put(509, "Purrloin");
        dexIdToName.put(510, "Liepard");
        dexIdToName.put(511, "Pansage");
        dexIdToName.put(512, "Simisage");
        dexIdToName.put(513, "Pansear");
        dexIdToName.put(514, "Simisear");
        dexIdToName.put(515, "Panpour");
        dexIdToName.put(516, "Simipour");
        dexIdToName.put(517, "Munna");
        dexIdToName.put(518, "Musharna");
        dexIdToName.put(519, "Pidove");
        dexIdToName.put(520, "Tranquill");
        dexIdToName.put(521, "Unfezant");
        dexIdToName.put(522, "Blitzle");
        dexIdToName.put(523, "Zebstrika");
        dexIdToName.put(524, "Roggenrola");
        dexIdToName.put(525, "Boldore");
        dexIdToName.put(526, "Gigalith");
        dexIdToName.put(527, "Woobat");
        dexIdToName.put(528, "Swoobat");
        dexIdToName.put(529, "Drilbur");
        dexIdToName.put(530, "Excadrill");
        dexIdToName.put(531, "Audino");
        dexIdToName.put(532, "Timburr");
        dexIdToName.put(533, "Gurdurr");
        dexIdToName.put(534, "Conkeldurr");
        dexIdToName.put(535, "Tympole");
        dexIdToName.put(536, "Palpitoad");
        dexIdToName.put(537, "Seismitoad");
        dexIdToName.put(538, "Throh");
        dexIdToName.put(539, "Sawk");
        dexIdToName.put(540, "Sewaddle");
        dexIdToName.put(541, "Swadloon");
        dexIdToName.put(542, "Leavanny");
        dexIdToName.put(543, "Venipede");
        dexIdToName.put(544, "Whirlipede");
        dexIdToName.put(545, "Scolipede");
        dexIdToName.put(546, "Cottonee");
        dexIdToName.put(547, "Whimsicott");
        dexIdToName.put(548, "Petilil");
        dexIdToName.put(549, "Lilligant");
        dexIdToName.put(550, "Basculin");
        dexIdToName.put(551, "Sandile");
        dexIdToName.put(552, "Krokorok");
        dexIdToName.put(553, "Krookodile");
        dexIdToName.put(554, "Darumaka");
        dexIdToName.put(555, "Darmanitan");
        dexIdToName.put(556, "Maractus");
        dexIdToName.put(557, "Dwebble");
        dexIdToName.put(558, "Crustle");
        dexIdToName.put(559, "Scraggy");
        dexIdToName.put(560, "Scrafty");
        dexIdToName.put(561, "Sigilyph");
        dexIdToName.put(562, "Yamask");
        dexIdToName.put(563, "Cofagrigus");
        dexIdToName.put(564, "Tirtouga");
        dexIdToName.put(565, "Carracosta");
        dexIdToName.put(566, "Archen");
        dexIdToName.put(567, "Archeops");
        dexIdToName.put(568, "Trubbish");
        dexIdToName.put(569, "Garbodor");
        dexIdToName.put(570, "Zorua");
        dexIdToName.put(571, "Zoroark");
        dexIdToName.put(572, "Minccino");
        dexIdToName.put(573, "Cinccino");
        dexIdToName.put(574, "Gothita");
        dexIdToName.put(575, "Gothorita");
        dexIdToName.put(576, "Gothitelle");
        dexIdToName.put(577, "Solosis");
        dexIdToName.put(578, "Duosion");
        dexIdToName.put(579, "Reuniclus");
        dexIdToName.put(580, "Ducklett");
        dexIdToName.put(581, "Swanna");
        dexIdToName.put(582, "Vanillite");
        dexIdToName.put(583, "Vanillish");
        dexIdToName.put(584, "Vanilluxe");
        dexIdToName.put(585, "Deerling");
        dexIdToName.put(586, "Sawsbuck");
        dexIdToName.put(587, "Emolga");
        dexIdToName.put(588, "Karrablast");
        dexIdToName.put(589, "Escavalier");
        dexIdToName.put(590, "Foongus");
        dexIdToName.put(591, "Amoonguss");
        dexIdToName.put(592, "Frillish");
        dexIdToName.put(593, "Jellicent");
        dexIdToName.put(594, "Alomomola");
        dexIdToName.put(595, "Joltik");
        dexIdToName.put(596, "Galvantula");
        dexIdToName.put(597, "Ferroseed");
        dexIdToName.put(598, "Ferrothorn");
        dexIdToName.put(599, "Klink");
        dexIdToName.put(600, "Klang");
        dexIdToName.put(601, "Klinklang");
        dexIdToName.put(602, "Tynamo");
        dexIdToName.put(603, "Eelektrik");
        dexIdToName.put(604, "Eelektross");
        dexIdToName.put(605, "Elgyem");
        dexIdToName.put(606, "Beheeyem");
        dexIdToName.put(607, "Litwick");
        dexIdToName.put(608, "Lampent");
        dexIdToName.put(609, "Chandelure");
        dexIdToName.put(610, "Axew");
        dexIdToName.put(611, "Fraxure");
        dexIdToName.put(612, "Haxorus");
        dexIdToName.put(613, "Cubchoo");
        dexIdToName.put(614, "Beartic");
        dexIdToName.put(615, "Cryogonal");
        dexIdToName.put(616, "Shelmet");
        dexIdToName.put(617, "Accelgor");
        dexIdToName.put(618, "Stunfisk");
        dexIdToName.put(619, "Mienfoo");
        dexIdToName.put(620, "Mienshao");
        dexIdToName.put(621, "Druddigon");
        dexIdToName.put(622, "Golett");
        dexIdToName.put(623, "Golurk");
        dexIdToName.put(624, "Pawniard");
        dexIdToName.put(625, "Bisharp");
        dexIdToName.put(626, "Bouffalant");
        dexIdToName.put(627, "Rufflet");
        dexIdToName.put(628, "Braviary");
        dexIdToName.put(629, "Vullaby");
        dexIdToName.put(630, "Mandibuzz");
        dexIdToName.put(631, "Heatmor");
        dexIdToName.put(632, "Durant");
        dexIdToName.put(633, "Deino");
        dexIdToName.put(634, "Zweilous");
        dexIdToName.put(635, "Hydreigon");
        dexIdToName.put(636, "Larvesta");
        dexIdToName.put(637, "Volcarona");
        dexIdToName.put(638, "Cobalion");
        dexIdToName.put(639, "Terrakion");
        dexIdToName.put(640, "Virizion");
        dexIdToName.put(641, "Tornadus");
        dexIdToName.put(642, "Thundurus");
        dexIdToName.put(643, "Reshiram");
        dexIdToName.put(644, "Zekrom");
        dexIdToName.put(645, "Landorus");
        dexIdToName.put(646, "Kyurem");
        dexIdToName.put(647, "Keldeo");
        dexIdToName.put(648, "Meloetta");
        dexIdToName.put(649, "Genesect");

        // Generation 6 (650-721)
        dexIdToName.put(650, "Chespin");
        dexIdToName.put(651, "Quilladin");
        dexIdToName.put(652, "Chesnaught");
        dexIdToName.put(653, "Fennekin");
        dexIdToName.put(654, "Braixen");
        dexIdToName.put(655, "Delphox");
        dexIdToName.put(656, "Froakie");
        dexIdToName.put(657, "Frogadier");
        dexIdToName.put(658, "Greninja");
        dexIdToName.put(659, "Bunnelby");
        dexIdToName.put(660, "Diggersby");
        dexIdToName.put(661, "Fletchling");
        dexIdToName.put(662, "Fletchinder");
        dexIdToName.put(663, "Talonflame");
        dexIdToName.put(664, "Scatterbug");
        dexIdToName.put(665, "Spewpa");
        dexIdToName.put(666, "Vivillon");
        dexIdToName.put(667, "Litleo");
        dexIdToName.put(668, "Pyroar");
        dexIdToName.put(669, "Flabébé");
        dexIdToName.put(670, "Floette");
        dexIdToName.put(671, "Florges");
        dexIdToName.put(672, "Skiddo");
        dexIdToName.put(673, "Gogoat");
        dexIdToName.put(674, "Pancham");
        dexIdToName.put(675, "Pangoro");
        dexIdToName.put(676, "Furfrou");
        dexIdToName.put(677, "Espurr");
        dexIdToName.put(678, "Meowstic");
        dexIdToName.put(679, "Honedge");
        dexIdToName.put(680, "Doublade");
        dexIdToName.put(681, "Aegislash");
        dexIdToName.put(682, "Spritzee");
        dexIdToName.put(683, "Aromatisse");
        dexIdToName.put(684, "Swirlix");
        dexIdToName.put(685, "Slurpuff");
        dexIdToName.put(686, "Inkay");
        dexIdToName.put(687, "Malamar");
        dexIdToName.put(688, "Binacle");
        dexIdToName.put(689, "Barbaracle");
        dexIdToName.put(690, "Skrelp");
        dexIdToName.put(691, "Dragalge");
        dexIdToName.put(692, "Clauncher");
        dexIdToName.put(693, "Clawitzer");
        dexIdToName.put(694, "Helioptile");
        dexIdToName.put(695, "Heliolisk");
        dexIdToName.put(696, "Tyrunt");
        dexIdToName.put(697, "Tyrantrum");
        dexIdToName.put(698, "Amaura");
        dexIdToName.put(699, "Aurorus");
        dexIdToName.put(700, "Sylveon");
        dexIdToName.put(701, "Hawlucha");
        dexIdToName.put(702, "Dedenne");
        dexIdToName.put(703, "Carbink");
        dexIdToName.put(704, "Goomy");
        dexIdToName.put(705, "Sliggoo");
        dexIdToName.put(706, "Goodra");
        dexIdToName.put(707, "Klefki");
        dexIdToName.put(708, "Phantump");
        dexIdToName.put(709, "Trevenant");
        dexIdToName.put(710, "Pumpkaboo");
        dexIdToName.put(711, "Gourgeist");
        dexIdToName.put(712, "Bergmite");
        dexIdToName.put(713, "Avalugg");
        dexIdToName.put(714, "Noibat");
        dexIdToName.put(715, "Noivern");
        dexIdToName.put(716, "Xerneas");
        dexIdToName.put(717, "Yveltal");
        dexIdToName.put(718, "Zygarde");
        dexIdToName.put(719, "Diancie");
        dexIdToName.put(720, "Hoopa");
        dexIdToName.put(721, "Volcanion");

        // Generation 7 (722-809)
        dexIdToName.put(722, "Rowlet");
        dexIdToName.put(723, "Dartrix");
        dexIdToName.put(724, "Decidueye");
        dexIdToName.put(725, "Litten");
        dexIdToName.put(726, "Torracat");
        dexIdToName.put(727, "Incineroar");
        dexIdToName.put(728, "Popplio");
        dexIdToName.put(729, "Brionne");
        dexIdToName.put(730, "Primarina");
        dexIdToName.put(731, "Pikipek");
        dexIdToName.put(732, "Trumbeak");
        dexIdToName.put(733, "Toucannon");
        dexIdToName.put(734, "Yungoos");
        dexIdToName.put(735, "Gumshoos");
        dexIdToName.put(736, "Grubbin");
        dexIdToName.put(737, "Charjabug");
        dexIdToName.put(738, "Vikavolt");
        dexIdToName.put(739, "Crabrawler");
        dexIdToName.put(740, "Crabominable");
        dexIdToName.put(741, "Oricorio");
        dexIdToName.put(742, "Cutiefly");
        dexIdToName.put(743, "Ribombee");
        dexIdToName.put(744, "Rockruff");
        dexIdToName.put(745, "Lycanroc");
        dexIdToName.put(746, "Wishiwashi");
        dexIdToName.put(747, "Mareanie");
        dexIdToName.put(748, "Toxapex");
        dexIdToName.put(749, "Mudbray");
        dexIdToName.put(750, "Mudsdale");
        dexIdToName.put(751, "Dewpider");
        dexIdToName.put(752, "Araquanid");
        dexIdToName.put(753, "Fomantis");
        dexIdToName.put(754, "Lurantis");
        dexIdToName.put(755, "Morelull");
        dexIdToName.put(756, "Shiinotic");
        dexIdToName.put(757, "Salandit");
        dexIdToName.put(758, "Salazzle");
        dexIdToName.put(759, "Stufful");
        dexIdToName.put(760, "Bewear");
        dexIdToName.put(761, "Bounsweet");
        dexIdToName.put(762, "Steenee");
        dexIdToName.put(763, "Tsareena");
        dexIdToName.put(764, "Comfey");
        dexIdToName.put(765, "Oranguru");
        dexIdToName.put(766, "Passimian");
        dexIdToName.put(767, "Wimpod");
        dexIdToName.put(768, "Golisopod");
        dexIdToName.put(769, "Sandygast");
        dexIdToName.put(770, "Palossand");
        dexIdToName.put(771, "Pyukumuku");
        dexIdToName.put(772, "Type: Null");
        dexIdToName.put(773, "Silvally");
        dexIdToName.put(774, "Minior");
        dexIdToName.put(775, "Komala");
        dexIdToName.put(776, "Turtonator");
        dexIdToName.put(777, "Togedemaru");
        dexIdToName.put(778, "Mimikyu");
        dexIdToName.put(779, "Bruxish");
        dexIdToName.put(780, "Drampa");
        dexIdToName.put(781, "Dhelmise");
        dexIdToName.put(782, "Jangmo-o");
        dexIdToName.put(783, "Hakamo-o");
        dexIdToName.put(784, "Kommo-o");
        dexIdToName.put(785, "Tapu Koko");
        dexIdToName.put(786, "Tapu Lele");
        dexIdToName.put(787, "Tapu Bulu");
        dexIdToName.put(788, "Tapu Fini");
        dexIdToName.put(789, "Cosmog");
        dexIdToName.put(790, "Cosmoem");
        dexIdToName.put(791, "Solgaleo");
        dexIdToName.put(792, "Lunala");
        dexIdToName.put(793, "Nihilego");
        dexIdToName.put(794, "Buzzwole");
        dexIdToName.put(795, "Pheromosa");
        dexIdToName.put(796, "Xurkitree");
        dexIdToName.put(797, "Celesteela");
        dexIdToName.put(798, "Kartana");
        dexIdToName.put(799, "Guzzlord");
        dexIdToName.put(800, "Necrozma");
        dexIdToName.put(801, "Magearna");
        dexIdToName.put(802, "Marshadow");
        dexIdToName.put(803, "Poipole");
        dexIdToName.put(804, "Naganadel");
        dexIdToName.put(805, "Stakataka");
        dexIdToName.put(806, "Blacephalon");
        dexIdToName.put(807, "Zeraora");
        dexIdToName.put(808, "Meltan");
        dexIdToName.put(809, "Melmetal");

        // Generation 8 (810-905)
        dexIdToName.put(810, "Grookey");
        dexIdToName.put(811, "Thwackey");
        dexIdToName.put(812, "Rillaboom");
        dexIdToName.put(813, "Scorbunny");
        dexIdToName.put(814, "Raboot");
        dexIdToName.put(815, "Cinderace");
        dexIdToName.put(816, "Sobble");
        dexIdToName.put(817, "Drizzile");
        dexIdToName.put(818, "Inteleon");
        dexIdToName.put(819, "Skwovet");
        dexIdToName.put(820, "Greedent");
        dexIdToName.put(821, "Rookidee");
        dexIdToName.put(822, "Corvisquire");
        dexIdToName.put(823, "Corviknight");
        dexIdToName.put(824, "Blipbug");
        dexIdToName.put(825, "Dottler");
        dexIdToName.put(826, "Orbeetle");
        dexIdToName.put(827, "Nickit");
        dexIdToName.put(828, "Thievul");
        dexIdToName.put(829, "Gossifleur");
        dexIdToName.put(830, "Eldegoss");
        dexIdToName.put(831, "Wooloo");
        dexIdToName.put(832, "Dubwool");
        dexIdToName.put(833, "Chewtle");
        dexIdToName.put(834, "Drednaw");
        dexIdToName.put(835, "Yamper");
        dexIdToName.put(836, "Boltund");
        dexIdToName.put(837, "Rolycoly");
        dexIdToName.put(838, "Carkol");
        dexIdToName.put(839, "Coalossal");
        dexIdToName.put(840, "Applin");
        dexIdToName.put(841, "Flapple");
        dexIdToName.put(842, "Appletun");
        dexIdToName.put(843, "Silicobra");
        dexIdToName.put(844, "Sandaconda");
        dexIdToName.put(845, "Cramorant");
        dexIdToName.put(846, "Arrokuda");
        dexIdToName.put(847, "Barraskewda");
        dexIdToName.put(848, "Toxel");
        dexIdToName.put(849, "Toxtricity");
        dexIdToName.put(850, "Sizzlipede");
        dexIdToName.put(851, "Centiskorch");
        dexIdToName.put(852, "Clobbopus");
        dexIdToName.put(853, "Grapploct");
        dexIdToName.put(854, "Sinistea");
        dexIdToName.put(855, "Polteageist");
        dexIdToName.put(856, "Hatenna");
        dexIdToName.put(857, "Hattrem");
        dexIdToName.put(858, "Hatterene");
        dexIdToName.put(859, "Impidimp");
        dexIdToName.put(860, "Morgrem");
        dexIdToName.put(861, "Grimmsnarl");
        dexIdToName.put(862, "Obstagoon");
        dexIdToName.put(863, "Perrserker");
        dexIdToName.put(864, "Cursola");
        dexIdToName.put(865, "Sirfetch'd");
        dexIdToName.put(866, "Mr. Rime");
        dexIdToName.put(867, "Runerigus");
        dexIdToName.put(868, "Milcery");
        dexIdToName.put(869, "Alcremie");
        dexIdToName.put(870, "Falinks");
        dexIdToName.put(871, "Pincurchin");
        dexIdToName.put(872, "Snom");
        dexIdToName.put(873, "Frosmoth");
        dexIdToName.put(874, "Stonjourner");
        dexIdToName.put(875, "Eiscue");
        dexIdToName.put(876, "Indeedee");
        dexIdToName.put(877, "Morpeko");
        dexIdToName.put(878, "Cufant");
        dexIdToName.put(879, "Copperajah");
        dexIdToName.put(880, "Dracozolt");
        dexIdToName.put(881, "Arctozolt");
        dexIdToName.put(882, "Dracovish");
        dexIdToName.put(883, "Arctovish");
        dexIdToName.put(884, "Duraludon");
        dexIdToName.put(885, "Dreepy");
        dexIdToName.put(886, "Drakloak");
        dexIdToName.put(887, "Dragapult");
        dexIdToName.put(888, "Zacian");
        dexIdToName.put(889, "Zamazenta");
        dexIdToName.put(890, "Eternatus");
        dexIdToName.put(891, "Kubfu");
        dexIdToName.put(892, "Urshifu");
        dexIdToName.put(893, "Zarude");
        dexIdToName.put(894, "Regieleki");
        dexIdToName.put(895, "Regidrago");
        dexIdToName.put(896, "Glastrier");
        dexIdToName.put(897, "Spectrier");
        dexIdToName.put(898, "Calyrex");
        dexIdToName.put(899, "Wyrdeer");
        dexIdToName.put(900, "Kleavor");
        dexIdToName.put(901, "Ursaluna");
        dexIdToName.put(902, "Basculegion");
        dexIdToName.put(903, "Sneasler");
        dexIdToName.put(904, "Overqwil");
        dexIdToName.put(905, "Enamorus");

        // Generation 9 (906-1025)
        dexIdToName.put(906, "Sprigatito");
        dexIdToName.put(907, "Floragato");
        dexIdToName.put(908, "Meowscarada");
        dexIdToName.put(909, "Fuecoco");
        dexIdToName.put(910, "Crocalor");
        dexIdToName.put(911, "Skeledirge");
        dexIdToName.put(912, "Quaxly");
        dexIdToName.put(913, "Quaxwell");
        dexIdToName.put(914, "Quaquaval");
        dexIdToName.put(915, "Lechonk");
        dexIdToName.put(916, "Oinkologne");
        dexIdToName.put(917, "Tarountula");
        dexIdToName.put(918, "Spidops");
        dexIdToName.put(919, "Nymble");
        dexIdToName.put(920, "Lokix");
        dexIdToName.put(921, "Pawmi");
        dexIdToName.put(922, "Pawmo");
        dexIdToName.put(923, "Pawmot");
        dexIdToName.put(924, "Tandemaus");
        dexIdToName.put(925, "Maushold");
        dexIdToName.put(926, "Fidough");
        dexIdToName.put(927, "Dachsbun");
        dexIdToName.put(928, "Smoliv");
        dexIdToName.put(929, "Dolliv");
        dexIdToName.put(930, "Arboliva");
        dexIdToName.put(931, "Squawkabilly");
        dexIdToName.put(932, "Nacli");
        dexIdToName.put(933, "Naclstack");
        dexIdToName.put(934, "Garganacl");
        dexIdToName.put(935, "Charcadet");
        dexIdToName.put(936, "Armarouge");
        dexIdToName.put(937, "Ceruledge");
        dexIdToName.put(938, "Tadbulb");
        dexIdToName.put(939, "Bellibolt");
        dexIdToName.put(940, "Wattrel");
        dexIdToName.put(941, "Kilowattrel");
        dexIdToName.put(942, "Maschiff");
        dexIdToName.put(943, "Mabosstiff");
        dexIdToName.put(944, "Shroodle");
        dexIdToName.put(945, "Grafaiai");
        dexIdToName.put(946, "Bramblin");
        dexIdToName.put(947, "Brambleghast");
        dexIdToName.put(948, "Toedscool");
        dexIdToName.put(949, "Toedscruel");
        dexIdToName.put(950, "Klawf");
        dexIdToName.put(951, "Capsakid");
        dexIdToName.put(952, "Scovillain");
        dexIdToName.put(953, "Rellor");
        dexIdToName.put(954, "Rabsca");
        dexIdToName.put(955, "Flittle");
        dexIdToName.put(956, "Espathra");
        dexIdToName.put(957, "Tinkatink");
        dexIdToName.put(958, "Tinkatuff");
        dexIdToName.put(959, "Tinkaton");
        dexIdToName.put(960, "Wiglett");
        dexIdToName.put(961, "Wugtrio");
        dexIdToName.put(962, "Bombirdier");
        dexIdToName.put(963, "Finizen");
        dexIdToName.put(964, "Palafin");
        dexIdToName.put(965, "Varoom");
        dexIdToName.put(966, "Revavroom");
        dexIdToName.put(967, "Cyclizar");
        dexIdToName.put(968, "Orthworm");
        dexIdToName.put(969, "Glimmet");
        dexIdToName.put(970, "Glimmora");
        dexIdToName.put(971, "Greavard");
        dexIdToName.put(972, "Houndstone");
        dexIdToName.put(973, "Flamigo");
        dexIdToName.put(974, "Cetoddle");
        dexIdToName.put(975, "Cetitan");
        dexIdToName.put(976, "Veluza");
        dexIdToName.put(977, "Dondozo");
        dexIdToName.put(978, "Tatsugiri");
        dexIdToName.put(979, "Annihilape");
        dexIdToName.put(980, "Clodsire");
        dexIdToName.put(981, "Farigiraf");
        dexIdToName.put(982, "Dudunsparce");
        dexIdToName.put(983, "Kingambit");
        dexIdToName.put(984, "Great Tusk");
        dexIdToName.put(985, "Scream Tail");
        dexIdToName.put(986, "Brute Bonnet");
        dexIdToName.put(987, "Flutter Mane");
        dexIdToName.put(988, "Slither Wing");
        dexIdToName.put(989, "Sandy Shocks");
        dexIdToName.put(990, "Iron Treads");
        dexIdToName.put(991, "Iron Bundle");
        dexIdToName.put(992, "Iron Hands");
        dexIdToName.put(993, "Iron Jugulis");
        dexIdToName.put(994, "Iron Moth");
        dexIdToName.put(995, "Iron Thorns");
        dexIdToName.put(996, "Frigibax");
        dexIdToName.put(997, "Arctibax");
        dexIdToName.put(998, "Baxcalibur");
        dexIdToName.put(999, "Gimmighoul");
        dexIdToName.put(1000, "Gholdengo");
        dexIdToName.put(1001, "Wo-Chien");
        dexIdToName.put(1002, "Chien-Pao");
        dexIdToName.put(1003, "Ting-Lu");
        dexIdToName.put(1004, "Chi-Yu");
        dexIdToName.put(1005, "Roaring Moon");
        dexIdToName.put(1006, "Iron Valiant");
        dexIdToName.put(1007, "Koraidon");
        dexIdToName.put(1008, "Miraidon");
        dexIdToName.put(1009, "Walking Wake");
        dexIdToName.put(1010, "Iron Leaves");
        dexIdToName.put(1011, "Dipplin");
        dexIdToName.put(1012, "Poltchageist");
        dexIdToName.put(1013, "Sinistcha");
        dexIdToName.put(1014, "Okidogi");
        dexIdToName.put(1015, "Munkidori");
        dexIdToName.put(1016, "Fezandipiti");
        dexIdToName.put(1017, "Ogerpon");
        dexIdToName.put(1018, "Archaludon");
        dexIdToName.put(1019, "Hydrapple");
        dexIdToName.put(1020, "Gouging Fire");
        dexIdToName.put(1021, "Raging Bolt");
        dexIdToName.put(1022, "Iron Boulder");
        dexIdToName.put(1023, "Iron Crown");
        dexIdToName.put(1024, "Terapagos");
        dexIdToName.put(1025, "Pecharunt");
    }
}